### ISSUE TITLE
Start Runner Error 

### ISSUE THREAD

**Issue by laxmanvallandas** [utilitywarehouse/semaphore-wireguard#22]
Tried to bring up the service with below config. Service is up, but the logs shows the error. 
Here is the below config used:
    {
      "local": {
        "name": "local" # name of the local cluster
      },
      "remotes": [
        {
          "name": "remote-aws-us-west-2.k8s.testing.com", # name of the remote cluster
          "kubeConfigPath": "/config", # kube config of remote cluster
          "podSubnet": "10.10.128.0/17",  # pod subnet of remote cluster
          "remoteSATokenPath": "/etc/semaphore-wireguard/tokens/remote1/token",
          "wgListenPort": 51821
        }
      ]
    }

Error in logs:

`2021-09-29T07:31:21.920Z [INFO]  semaphore-wireguard: Could not get wg device by name, will try creating: name=wireguard.remote-aws-us-west-2.k8s.testing.com err="numerical result out of range"
2021-09-29T07:31:21.921Z [ERROR] semaphore-wireguard: Retry failed: description="start runner" error="numerical result out of range" backoff=2s
E0929 07:31:21.925119       1 cert_rotation.go:168] key failed with : tls: failed to find any PEM data in certificate input
E0929 07:31:21.935465       1 cert_rotation.go:168] key failed with : tls: failed to find any PEM data in certificate input`

Am i missing something from the configuration?

**Comment by laxmanvallandas** [comment]
One more query:
Is the node annotation is the prerequisite in both clusters? if so, how does that annotation would look like. (Sorry, haven't used annotations much before).
`
for local: <local-name>.wireguard.semaphore.uw.io: "true" AND 
for remote: <remote-name>.wireguard.semaphore.uw.io: "true" 
`?

**Comment by george-angel** [comment]
```
2021-09-29T07:31:21.920Z [INFO] semaphore-wireguard: Could not get wg device by name, will try creating: name=wireguard.remote-aws-us-west-2.k8s.testing.com err="numerical result out of range"
```

Aha - we need to have better validation of device names, I think thats too rich for a Linux device name. Can you please try something simple like `rem` for remote name?

**Comment by ffilippopoulos** [comment]
> Is the node annotation is the prerequisite in both clusters? 

No, the daemosnset will be creating the needed annotations on nodes. One thing to note here is that you need to be consistent on cluster names between configurations, as they will be used to look for the respective annotations. So, if you actually name all local clusters as "local" the operator will not be able to go and find the correct keys, as it will be looking for local.wireguard.semaphore.uw.io annotations on remote nodes. You need to pick cluster names that will be unique and consistent across configurations in different clusters.

Regarding the error posted on the description, as replied above ^, semaphore-wireguard will try to create a network interface named: wireguard.<remote-cluster-name> (in your case wireguard.remote-aws-us-west-2.k8s.testing.com) and there should be a maximum length allowed by NETLINK. Setting simpler as suggested above should allow creation of the wg interface.

**Comment by laxmanvallandas** [comment]
Thanks for looking and providing the details on annotations.
Renaming to a shorter gives another error:
`
E0929 16:23:42.488148       1 cert_rotation.go:168] key failed with : tls: failed to find any PEM data in certificate input
2021-09-29T16:23:43.219Z [INFO]  semaphore-wireguard: Could not get wg device by name, will try creating: name=wireguard.rem err="Link not found"
2021-09-29T16:23:43.221Z [ERROR] semaphore-wireguard: Retry failed: description="start runner" **error="operation not supported"** backoff=3.881018176s` . Seems like am missing to provide permissions?

**Comment by george-angel** [comment]
Can you please share the contents of:

- `/config`
- `/etc/semaphore-wireguard/tokens/remote1/token`

From inside the container, redacting sensitive values. For the token - you can use https://jwt.io/ - to get a readable format that redacts sensitive infromation.

**Comment by ffilippopoulos** [comment]
`error="operation not supported"*"`
@laxmanvallandas also, let me state the obvious here, this assumes that you have wireguard kernel module loaded in your kubernetes hosts.  And presumably your pods have access to the hosts' network interfaces: https://github.com/utilitywarehouse/semaphore-wireguard/blob/main/deploy/example/namespace/daemonset.yaml#L17

**Comment by ffilippopoulos** [comment]
Is your daemonset configured to use the host network too: `hostNetwork: true`?
And do you have the ability to create wireguard interfaces on your hosts? Can you try `sudo modprobe wireguard` to make sure the module is loaded on the host machines? What kernel are your hosts on?

**Comment by laxmanvallandas** [comment]
> Is your daemonset configured to use the host network too: hostNetwork: true?
Yes. 

 Kernel module(wireguard) is not present on my host. That's the root cause. 
 I am using:
Kernel Version: Linux 3.10.0 (x86_64) on centos7
[~]# ip link add dev wg0 type wireguard
RTNETLINK answers: Operation not supported => Exact error from the logs

**Comment by laxmanvallandas** [comment]
Issue resolved after installing wireguard module. 
Service is up and running.

**Comment by ffilippopoulos** [comment]
Merged this one: https://github.com/utilitywarehouse/semaphore-wireguard/pull/23 so hopefully the next release will give a nicer experience when debugging runners startup errors.
@laxmanvallandas let us know if you have a successful deployment or do not hesitate to raise issues if you need more support to get a successful cross cluster setup.
